version: "3.8"

services:
  app:
    build: .
    ports:
      - "8082:8082" 
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Quiz
      - SPRING_DATASOURCE_USERNAME=pruthvi1405
      - SPRING_DATASOURCE_PASSWORD=Poojan123
  
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=pruthvi1405
      - POSTGRES_PASSWORD=Poojan123
      - POSTGRES_DB=Quiz